#################
### AUTOSTART ###
#################


# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = swww & disown
exec-once = waypaper --restore
# Avvia Elephant come servizio (se non lo hai già fatto con systemctl)
exec-once = elephant
exec-once = eww daemon
exec-once = waybar
exec-once = clipse -listen
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = powerprofilesctl set balanced
