#################################
### CONFIGURAZIONE DI PIRAZZI ###
#################################

# --- Programmi Predefiniti ---
$terminal = kitty
$fileManager = nautilus
$menu = ~/.config/rofi/launchers/type-2/launcher.sh

# --- Caricamento Moduli Esterni ---
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/bind.conf
source = ~/.config/hypr/ui.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/rules.conf

#############################
### IMPOSTAZIONI MISC     ###
#############################
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}
