general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    # Se hai uno sfondo specifico, metti il percorso qui sotto
    # Altrimenti lascia un colore solido Tokyo Night
    color = rgba(26, 27, 38, 1.0) 
    blur_passes = 2
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(122, 162, 247) # Blue
    inner_color = rgb(26, 27, 38)    # Background
    font_color = rgb(192, 202, 245)  # Foreground
    fade_on_empty = true
    placeholder_text = <i>Inserisci Password...</i>
    hide_input = false
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(187, 154, 247) # Magenta
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}
